//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CodePrinter.rc
//
#define IDD_CODEPRINTER_DIALOG          102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDB_BITMAP1                     129
#define IDB_BITMAP2                     130
#define IDB_BITMAP3                     131
#define IDD_LABEL_DIALOG                132
#define IDD_CONFIGURATION_DIALOG        133
#define IDD_FILEMANA_DIALOG             134
#define IDD_INKSYSTEM_DIALOG            135
#define IDD_INPUT_DIALOG                136
#define IDD_EDITTEXT_DIALOG             137
#define IDD_EDITFIGURE_DIALOG           138
#define IDD_DATE_DLG                    139
#define IDD_DATE_DIALOG                 139
#define IDD_PICTURE_DIALOG              140
#define IDD_BARCODE_DIALOG              141
#define IDD_ENV_DIALOG                  142
#define IDD_COM_DIALOG                  143
#define IDD_SYSTEM_DIALOG               145
#define IDD_FAULT_DIALOG                146
#define IDD_USER_DIALOG                 147
#define IDD_VERSION_DIALOG              148
#define IDD_USER_OPEN_DIALOG            149
#define IDD_USER_NEW_DIALOG             150
#define IDD_USER_DELETE_DIALOG          151
#define IDD_USER_FRESH_DIALOG           152
#define IDC_FAULT_BUTTON                1001
#define IDC_USER_BUTTON                 1002
#define IDC_LABEL_BUTTON                1003
#define IDC_CONFIGURATION_BUTTON        1004
#define IDC_FILEMANA_BUTTON             1005
#define IDC_LSELECT_BUTTON              1006
#define IDC_RSELECT_BUTTON              1007
#define IDC_COMBOMATRIX                 1008
#define Static_Matrix                   1009
#define IDC_PIXEL_STATIC                1010
#define IDC_COMBO2                      1011
#define Static_Reversal                 1012
#define IDC_COMBO3                      1013
#define Static_Perversion               1014
#define IDC_COMBO4                      1015
#define Input_Button                    1016
#define Edit_Show                       1017
#define Abc_Button                      1018
#define IDC_EDITFIGURE_BUTTON           1019
#define IDC_EDITDATE_BUTTON             1020
#define IDC_EDITPICTURE_BUTTON          1021
#define Bar_Code_Button                 1022
#define Odbc_Button                     1023
#define IDC_COPY_BUTTON                 1024
#define IDC_DELETE_BUTTON               1025
#define IDC_REPEAT_BUTTON               1026
#define IDC_SHRINK_BUTTON               1027
#define IDC_ZOOM_BUTTON                 1028
#define IDC_CLOSE_BUTTON                1029
#define IDC_FAR_BUTTON                  1030
#define Button1                         1031
#define Button2                         1032
#define IDC_UDMIRROR_BUTTON             1033
#define IDC_LRMIRROR_BUTTON             1034
#define IDC_DOWNLOAD_BUTTON             1035
#define IDC_CLS_BUTTON                  1036
#define IDC_ODBC_BUTTON                 1037
#define IDC_SAVE_BUTTON                 1038
#define Static_Text                     1039
#define Static_Font                     1040
#define IDC_EDIT5                       1041
#define IDC_EDIT1                       1042
#define IDC_EDIT2                       1043
#define IDC_EDIT3                       1044
#define IDC_EDIT4                       1045
#define IDC_STATIC_DESIGN_AREA          1046
#define IDC_LIST2                       1048
#define IDC_PRINT_PRE_STATIC            1051
#define IDC_TIME_STATIC                 1052
#define IDC_RESET_COUNT_BTN             1053
#define IDC_RESET_SERIAL_BTN            1054
#define IDC_BUTTON1                     1055
#define IDC_BUTTON2                     1056
#define IDC_NEW_BTN                     1057
#define IDC_EDIT7                       1058
#define IDC_USER_FRESH_BTN              1059
#define IDC_BUTTON13                    1060
#define IDC_BUTTON10                    1061
#define IDC_LIST1                       1062
#define IDC_BUTTON4                     1063
#define IDC_BUTTON5                     1064
#define IDC_BUTTON6                     1065
#define IDC_CUSTONBUTTON                1065
#define IDC_CUSTON_BUTTON               1065
#define IDC_BUTTON7                     1066
#define IDC_VERSION_BTN                 1066
#define IDC_BUTTON9                     1068
#define IDC_EVN_BTN                     1074
#define IDC_COMBO1                      1075
#define IDC_COUNTER_COMBO               1075
#define IDC_DATE_FONT_COMBO             1075
#define IDC_BARCODE_VERSION_COMBO       1075
#define IDC_LANGUAGE_STATIC             1076
#define IDC_SYSTEM_CANCEL_BTN           1077
#define IDC_SYSTEM_CLOSE_BTN            1077
#define IDC_SPIN2                       1080
#define IDC_INK_BUTTON                  1081
#define IDC_CODEPRINTER_TYPE_STATIC     1081
#define IDC_SYSTEM_BUTTON               1082
#define IDC_CODEPRINTE_ID_RSTATIC       1082
#define IDC_MATRIX                      1083
#define IDC_MAINBOARD_ID_STATIC         1083
#define IDC_MATRIX_STATIC               1084
#define IDC_MAINBOARD_HARDWARE_TYPE_STATIC 1084
#define Static_Pixel                    1085
#define IDC_HARDWARE_UPDATE_TIME_STATIC 1085
#define IDC_REVERSAL_STATIC             1086
#define IDC_MAINBOARD_SOFTWARE_TYPE_STATIC 1086
#define IDC_PERVERSION_STATIC           1087
#define IDC_SOFTWARE_UPDATE_TIME_STATIC 1087
#define IDC_INPUT_BUTTON                1088
#define IDC_SHOW_EDIT                   1089
#define U_Shift_Button                  1090
#define IDC_USHIFT_BUTTON               1091
#define IDC_EDITTEXT_BUTTON             1092
#define Figure_Button                   1093
#define D_Shift_Button                  1094
#define IDC_DSHIFT_BUTTON               1095
#define Date_Button                     1096
#define L_Shift_Button                  1097
#define IDC_LSHIFT_BUTTON               1098
#define Picture_Button                  1099
#define R_Shift_Button                  1100
#define IDC_RSHIFT_BUTTON               1101
#define L_Qshift_Button                 1102
#define IDC_LQSHIFT_BUTTON              1103
#define IDC_BARCODE_BUTTON              1104
#define R_QShift_Button                 1105
#define IDC_RQSHIFT_BUTTON              1106
#define Copy_Button                     1107
#define Delete_Button                   1108
#define Repeat_Button                   1109
#define Shrink_Button                   1110
#define Zoom_Button                     1111
#define Close_Button                    1112
#define Far_Button                      1113
#define LR_Mirror_Button                1115
#define Download_Button                 1116
#define Cls_Button                      1117
#define Open_Button                     1118
#define IDC_OPEN_BUTTON                 1119
#define Save_Button                     1120
#define IDC_COMBO_MATRIX                1121
#define Static_DataField                1122
#define Combo_Font                      1123
#define IDC_EDIT6                       1124
#define IDC_DELETE_BTN                  1125
#define IDC_BUTTON3                     1126
#define IDC_LANGUAGE_COMBO              1127
#define IDC_SYSTEM_SOFTWARE_TYPE_STATIC 1128
#define IDC_SYSTEM_SOFTWARE_UPDATE_TIME_STATIC 1129
#define IDC_OPEN_BTN                    1130
#define IDC_COM_BTN                     1131
#define IDC_CLOSE_USER_BTN              1132
#define IDC_NET_BTN                     1133
#define IDC_LABEL_CLOSE_BTN             1134
#define IDC_INPUT_CLOSE_BTN             1135
#define IDC_EDITTEXT_CLOSE_BTN          1136
#define IDC_EDITFIG_CLOSE_BTN           1137
#define IDC_PREVIEW_STATIC              1138
#define IDC_FIRST_QUARTILE_STATIC       1139
#define IDC_FOUR_QUARTILE_STATIC        1140
#define IDC_START_STATIC                1141
#define IDC_STEP_SIZE_STATIC            1142
#define IDC_PREVIEW_EDIT                1144
#define IDC_FIRST_QUARTILE_EDIT         1145
#define IDC_FOUR_QUARTILE_EDIT          1146
#define IDC_START_EDIT                  1147
#define IDC_STEP_SIZE_EDIT              1148
#define IDC_REPEAT_COUNT_STATIC         1149
#define IDC_REPEAT_COUNT_EDIT           1150
#define IDC_BIT_DATA_EDIT               1151
#define IDC_BIT_DATA_STATIC             1152
#define IDC_COUNTER_STATIC              1153
#define IDC_FONT_STATIC                 1155
#define IDC_FONT_COMBO                  1156
#define IDC_FORMAT_STATIC               1157
#define IDC_FORMAT_COMBO                1158
#define IDC_DATE_PREVIEW_STATIC         1159
#define IDC_DATE_FORMAT_STATIC          1160
#define IDC_DATE_ADD_BTN                1161
#define IDC_DATE_FONT_STATIC            1162
#define IDC_DATE_SKEW_STATIC            1163
#define IDC_DATE_SKEW_COMBO             1164
#define IDC_DATE_SKEW_VALUE_STATIC      1165
#define IDC_DATE_SKEW_VALUE_EDIT        1166
#define IDC_DATE_SKEW_UNIT_STATIC       1167
#define IDC_DATE_CLOSE_BTN              1168
#define IDC_DATE_REFRESH_BTN            1169
#define IDC_DATE_OK_BTN                 1170
#define IDC_PICTURE_CLOSE_BUTTON        1171
#define IDC_BARCODE_CLOSE_BTN           1172
#define IDC_BARCODE_TEXT_STATIC         1173
#define IDC_BARCODE_TEXT_EDIT           1174
#define IDC_BARCODE_SET_STATIC          1175
#define IDC_ECC_LEVEL_STATIC            1176
#define IDC_QUIET_ZONE_STATIC           1177
#define IDC_BARCODE_ECC_LEV_COMBO       1178
#define IDC_BARCODE_ZONE_COMBO          1179
#define IDC_BARCODE_FIGURE_BTN          1180
#define IDC_BARCODE_DATE_BTN            1181
#define IDC_BARCODE_OK_BTN              1182
#define IDC_QR_CODE_BTN                 1183
#define IDC_                            1184
#define IDC_DATA_MATRIX_BTN             1184
#define IDC_CODE_39_BTN                 1185
#define IDC_CODE_128_BTN                1186

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        153
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1187
#define _APS_NEXT_SYMED_VALUE           148
#endif
#endif
